import { chromium } from "@playwright/test";
const shots = process.env.SHOTS;
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
page.on("console", (m) => { if (m.type() === "error") errors.push(m.text()); });
const email = `smoke${Date.now()}@example.test`;
await page.goto("http://localhost:3000/sign-up");
await page.getByLabel("Email").fill(email);
await page.getByLabel("Password").fill("correct horse battery");
await page.getByRole("button", { name: "Create account" }).click();
await page.waitForURL(/onboarding/, { timeout: 30000 });
await page.getByLabel("Business name").fill("Smoke Bar");
await page.getByRole("button", { name: "Create" }).click();
await page.waitForURL(/today/, { timeout: 30000 });
console.log("landed", page.url(), await page.locator("h1").innerText());
await page.screenshot({ path: `${shots}/smoke-today.png` });
console.log("console errors:", errors);
await browser.close();
